remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

is_project_page: false
is_user_page: true

title: "Hebert L Silva"
description: "Minha pagina pessoal e meio que um curr√≠culo"


# share-links-active:
#   twitter: true
#   facebook: true
#   linkedin: true

social-network-links:
  email: "hebert.luiz.hb@gmail.com"
  facebook: cienlouco
  github: hebertluiz
  twitter: cienlouco
  patreon: hevsavets
  instagram: cienlouco
  telegram: cienlouco
  
